package lk.ijse.raviMotors.util;

public enum Routes {

   DASHBOAD,CUSTOMER,EMPLOYEE,LOGIN,SUPPLIER,DASHBOADRECEPTION,ORDER,PART,FINACE,MONTHLYREPORT,ANNUALREPORT,PANEDASHBOAD,PLACEORDER,ORDERDETAIL
}
